<?php
/**
 * Holds the permission configuration files.
 */
$permission['index'] = array('admin', 'user');
$permission['logout'] = array('admin', 'user');
$permission['login'] = array('admin', 'user');
$permission['change_password'] = array('admin', 'user');
$permission['add_user'] = array('admin');
$permission['disable_user'] = array('admin');
$permission['disabled_users'] = array('admin');
$permission['edit_user'] = array('admin');
$permission['list_users'] = array('admin');
$permission['add_bill'] = array('admin', 'user');
$permission['search_bill'] = array('admin', 'user');
$permission['cancel_bill'] = array('admin', 'user');
$permission['list_customer'] = array('admin');
$permission['disable_customer'] = array('admin');
$permission['disabled_customers'] = array('admin');
$permission['add_customer'] = array('admin', 'user');
$permission['add_item'] = array('admin');
$permission['edit_item'] = array('admin');
$permission['list_items'] = array('admin','user');
$permission['disabled_items'] = array('admin');
$permission['add_stock'] = array('admin', 'user');
$permission['process_items'] = array('admin');
$permission['report'] = array('admin');
?>

